#!/bin/bash

# a script to locally build all targets using podman or docker

# set TARGET_ARCHITECTURE to rtems for RTEMS based targets
T_A=${TARGET_ARCHITECTURE:-linux}
# set TARGET to runtime for runtime images
TARGET=${TARGET:-developer}
# set TAG to override the default tag
TAG=${TAG:-ec_test}

# log commands and stop on erros
set -xe

cd $(dirname ${0})

# use docker if available else use podman
if ! docker version &>/dev/null; then docker=podman; else docker=docker; fi

# make sure new repos get their submodule ibek-support
git submodule update --init

# build and developer images
$docker build --network host --target $TARGET \
        --build-arg TARGETARCH=amd64 \
        --build-arg TARGET_ARCHITECTURE=$T_A \
        -t ${TAG} .
