#!/bin/bash

# a script to locally build all targets containers for this IOC

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd ${THIS_DIR}

set -xe

if [[ -z ${TARGET_ARCHITECTURE} || ${TARGET_ARCHITECTURE}=="linux" ]]; then
podman build --target developer --build-arg TARGET_ARCHITECTURE=linux -t epics-base-linux-developer .
podman build --target runtime --build-arg TARGET_ARCHITECTURE=linux -t epics-base-linux-runtime .
fi

if [[ -z ${TARGET_ARCHITECTURE} || ${TARGET_ARCHITECTURE}=="rtems" ]]; then
podman build --target developer --build-arg TARGET_ARCHITECTURE=rtems -t epics-base-rtems-developer .
podman build --target runtime --build-arg TARGET_ARCHITECTURE=rtems -t epics-base-rtems-runtime .
fi
