#!/bin/bash

# Custom initialization goes here if needed.
# Runs inside the dev container after the container is created

################################################################################
# When using docker we will not be root inside the container
# the following steps are then required
################################################################################

if [[ $(id -u) != "0" ]] ; then
    # make sure the non-root user can build iocs and (mounted in) support modules
    sudo chown -R ${USER}:${USER} /epics/ibek-defs /epics/pvi-defs /epics/support/configure /venv
    sudo chown -h ${USER}:${USER} /epics /epics/ioc /epics/support
fi
